# Generated by Django 5.2.6 on 2026-08-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token_jti',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
