# Generated by Django 5.2.6 on 2026-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp_reset_token_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
