# Generated by Django 5.2.6 on 2026-08-11 16:57

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.validators.vehicle_registration_validator]),
        ),
    ]
