# Generated by Django 5.2.6 on 2026-08-19 09:57

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_vehicle_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='phone',
            field=models.CharField(max_length=15, validators=[accounts.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[accounts.validators.phone_number_validator]),
        ),
    ]
