# Generated by Django 5.2.6 on 2026-08-19 11:04

import accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone_verified_alter_pendingregistration_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[accounts.validators.phone_number_validator])),
                ('otp_hash', models.CharField(max_length=255)),
                ('otp_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
