# Generated by Django 5.2.6 on 2026-08-20 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phoneverificationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChangeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('new_contact', models.CharField(max_length=254)),
                ('otp_hash', models.CharField(max_length=255)),
                ('otp_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_change_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
