# Generated by Django 5.2.6 on 2026-08-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contactchangeotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
