# Generated by Django 5.2.6 on 2026-08-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='parking.parkingarea')),
            ],
            options={
                'ordering': ['floor_number'],
                'constraints': [models.UniqueConstraint(fields=('parking_area', 'floor_number'), name='unique_floor_per_parking_area')],
            },
        ),
    ]
