# Generated by Django 5.2.6 on 2026-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingfloor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingfloor',
            name='floor_number',
            field=models.IntegerField(),
        ),
    ]
