from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    RegisterView,
    VerifyOTPView,
    LoginView,
    ForgotPasswordAPIView,
    VerifyResetOTPAPIView,
    ResetPasswordAPIView,
    ResendResetOTPAPIView,
    ProfileView,
    VehicleListCreateView,
    VehicleDetailView,
    SetDefaultVehicleView,
    SendPhoneVerificationOTPView,
    VerifyPhoneOTPView,
    ResendPhoneVerificationOTPView,
    ChangePhoneNumberView,
    VerifyPhoneNumberChangeView,
)

urlpatterns = [
    path("register/",RegisterView.as_view(),name = "register",),
    path("verify-otp/",VerifyOTPView.as_view(),name="verify-otp"),
    path("login/",LoginView.as_view(),name="login",),
    path("token/refresh/",TokenRefreshView.as_view(),name="token-refresh",),
    path("forgot-password/",ForgotPasswordAPIView.as_view(),name="forgot-password",),
    path("verify-reset-otp/",VerifyResetOTPAPIView.as_view(),name="verify-reset-otp",),
    path("reset-password/",ResetPasswordAPIView.as_view(),name="reset-password"),
    path( "resend-reset-otp/", ResendResetOTPAPIView.as_view(), name="resend-reset-otp" ),
    path("profile/",ProfileView.as_view(),name="profile"),
    path("vehicles/",VehicleListCreateView.as_view(),name="vehicle-list-create"),
    path("vehicles/<int:pk>/",VehicleDetailView.as_view(),name="vehicle-detail"),
    path("vehicles/<int:pk>/set-default/",SetDefaultVehicleView.as_view(),name="vehicle-set-default"),
    path("phone/send-otp/",SendPhoneVerificationOTPView.as_view(),name="send-phone-verification-otp",),
    path("phone/verify-otp/",VerifyPhoneOTPView.as_view(),name="verify-phone-otp",),
    path("phone/resend-otp/",ResendPhoneVerificationOTPView.as_view(),name="resend-phone-verification-otp",),
    path("phone/change/",ChangePhoneNumberView.as_view(),name="change-phone-number"),
    path("phone/change/verify-otp/",VerifyPhoneNumberChangeView.as_view(),name="verify-phone-number-change"),
]